"""
business_calendar_data.py -- backend-importable port of the frontend's
embedded BUSINESS_CALENDAR object (indiapulse-mockup.html). Straight
structural copy, NOT regenerated -- this is curated, training-knowledge-
only judgment (draft v0.2 per the frontend's own comment), the same
content, unchanged. business_score.py imports this directly:

    from business_calendar_data import BUSINESS_CALENDAR

Shape: {category_name: {'states': [12 x Peak|Strong|Normal|Weak|Recovery],
'confidence': 'high'|'medium'|'low', 'why': [12 rationale strings]}},
index 0=Jan..11=Dec. Validated at generation time: every entry has exactly
12 states and 12 rationale strings, states are drawn only from the 5 known
labels, confidence is one of the 3 known tiers. 38 categories covered --
Broad Market, Market Cap, Strategy, Global Markets, Innovation, and
Logistics categories are intentionally absent (out of curated scope, see
the frontend's own comment above BUSINESS_CALENDAR) and correctly fall
back to None in business_score.compute_effective_business_score().

Star-rank reference (BUSINESS_RANK, also embedded in the frontend, used
here to confirm business_score.py's STATE_SCORES ordering matches):
    Weak=0, Recovery=1, Normal=2, Strong=3, Peak=4
"""

BUSINESS_CALENDAR = {
  'Banking':            {'states':['Strong','Strong','Peak','Normal','Normal','Weak','Weak','Recovery','Recovery','Strong','Strong','Strong'], 'confidence':'high',
    'why':['Budget-linked rate positioning by lenders','Pre-Budget credit demand firms up','FY-end quarter-end credit push','Post FY-end, steady baseline lending','Steady credit growth, no major catalyst','Pre-monsoon loan demand lull','Monsoon slows retail credit uptake','Credit demand rebuilding post-monsoon','Pre-festive credit demand improving','Festive personal & auto loan demand','Festive lending season continues','Wedding-season personal loan demand']},
  'Private Banks':      {'states':['Strong','Strong','Peak','Normal','Normal','Weak','Weak','Recovery','Recovery','Strong','Strong','Strong'], 'confidence':'high',
    'why':['Budget-linked rate positioning by lenders','Pre-Budget credit demand firms up','FY-end quarter-end credit push','Post FY-end, steady baseline lending','Steady credit growth, no major catalyst','Pre-monsoon loan demand lull','Monsoon slows retail credit uptake','Credit demand rebuilding post-monsoon','Pre-festive credit demand improving','Festive personal & auto loan demand','Festive lending season continues','Wedding-season personal loan demand']},
  'PSU Banks':          {'states':['Recovery','Strong','Strong','Normal','Normal','Weak','Weak','Weak','Recovery','Recovery','Normal','Normal'], 'confidence':'medium',
    'why':['Demand picks up ahead of Budget','Budget recap/divestment news lifts sentiment','FY-end priority-sector lending push','Post FY-end, steady baseline','No major catalyst this month','Pre-monsoon lending slowdown','Monsoon dampens credit offtake','Continued monsoon-related lull','Pre-festive credit demand improving','Early festive lending pickup','Festive demand normalizes','Steady year-end lending activity']},
  'Financial Services': {'states':['Strong','Strong','Peak','Weak','Weak','Normal','Normal','Normal','Recovery','Strong','Strong','Strong'], 'confidence':'high',
    'why':['80C tax-saving inflows begin','Tax-saving season builds momentum','80C deadline rush, FY-end MF flows','Post tax-season lull','Seasonal trough, no major inflows','Steady baseline activity','No major catalyst this month','Steady flows, pre-festive positioning','Festive-linked flows start improving','Festive FII inflows pick up','Continued festive-season flows','Year-end FII/FPI positioning']},
  'Capital Markets':    {'states':['Strong','Normal','Strong','Weak','Weak','Normal','Normal','Recovery','Recovery','Strong','Strong','Peak'], 'confidence':'medium',
    'why':['New-year IPO pipeline activity','Steady baseline trading activity','FY-end mutual fund flow push','Post FY-end volume lull','Seasonal trading lull','No major catalyst this month','Steady baseline activity','Volumes start rebuilding','Pre-festive activity improving','Festive-season trading pickup','Continued strong trading volumes','Year-end IPO/rally activity peaks']},
  'Information Technology': {'states':['Strong','Normal','Normal','Weak','Weak','Recovery','Recovery','Normal','Normal','Strong','Strong','Peak'], 'confidence':'high',
    'why':['Q4 results/guidance set tone','Steady baseline, no major catalyst','FY-end, steady execution','New fiscal-year client budget uncertainty','Client budget cycles still settling','Client spending starts firming up','Q1 results improve visibility','Steady baseline activity','No major catalyst this month','US client budget planning ramps up','Deal pipeline builds into year-end','US client CY-end budget flush']},
  'Pharma':             {'states':['Normal','Normal','Normal','Recovery','Normal','Normal','Strong','Strong','Normal','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Steady, largely non-seasonal demand','Steady, largely non-seasonal demand','Steady, largely non-seasonal demand','Early pre-monsoon stocking begins','Steady baseline demand','Steady baseline demand','Monsoon-linked acute illness demand rises','Continued monsoon illness-driven demand','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline']},
  'Healthcare':         {'states':['Normal','Normal','Normal','Normal','Weak','Recovery','Strong','Strong','Normal','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Steady, largely non-seasonal demand','Steady, largely non-seasonal demand','Steady, largely non-seasonal demand','Steady, largely non-seasonal demand','Pre-monsoon seasonal lull','Admissions start picking up','Monsoon illness/hospital admission bump','Continued monsoon-linked admissions','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline','Demand normalizes, defensive baseline']},
  'FMCG':               {'states':['Normal','Normal','Weak','Weak','Recovery','Recovery','Normal','Strong','Strong','Peak','Peak','Strong'], 'confidence':'high',
    'why':['Steady baseline consumption','Steady baseline, no major catalyst','Post-holiday, pre-summer lull','Summer heat softens footfall','Pre-monsoon stocking begins','Demand starts rebuilding','Steady monsoon-season baseline','Pre-festive stocking ramps up','Festive inventory build continues','Diwali festive demand peaks','Post-Diwali & wedding season demand','Wedding-season consumption remains elevated']},
  'Consumption':        {'states':['Normal','Normal','Weak','Weak','Recovery','Recovery','Normal','Strong','Strong','Peak','Peak','Strong'], 'confidence':'high',
    'why':['Steady baseline consumption','Steady baseline, no major catalyst','Post-holiday, pre-summer lull','Summer heat softens footfall','Pre-monsoon stocking begins','Demand starts rebuilding','Steady monsoon-season baseline','Pre-festive stocking ramps up','Festive inventory build continues','Diwali festive demand peaks','Post-Diwali & wedding season demand','Wedding-season consumption remains elevated']},
  'Auto':               {'states':['Recovery','Normal','Normal','Weak','Weak','Weak','Recovery','Recovery','Strong','Peak','Peak','Strong'], 'confidence':'high',
    'why':['New-year model launches lift footfall','Steady baseline sales','FY-end dealer stocking, steady demand','Post FY-end sales lull','Summer heat softens showroom footfall','Monsoon rural-demand uncertainty','Rural sentiment starts improving','Pre-festive bookings pick up','Navratri auspicious-buying demand','Festive Diwali sales peak','Continued festive & wedding-season demand','Wedding-season bookings remain elevated']},
  'Infrastructure':     {'states':['Strong','Strong','Peak','Normal','Normal','Weak','Weak','Weak','Recovery','Recovery','Normal','Normal'], 'confidence':'medium',
    'why':['Pre-Budget capex positioning','Union Budget infra allocation lifts orders','FY-end execution push on order books','Post FY-end, steady execution','Steady baseline execution','Monsoon halts construction activity','Continued monsoon construction halt','Monsoon-related execution delays persist','Post-monsoon execution resumes','Site activity continues rebuilding','Steady baseline execution','Steady year-end execution']},
  'Metals':             {'states':['Normal','Recovery','Strong','Strong','Normal','Weak','Weak','Recovery','Normal','Normal','Recovery','Normal'], 'confidence':'low',
    'why':['Steady baseline, global-price driven','China restocking demand begins','China construction-season restocking','Continued China restocking demand','Demand normalizes post-restocking','Monsoon slows domestic construction','Continued monsoon construction slowdown','Domestic demand starts rebuilding','Steady baseline, global-price driven','Steady baseline demand','Post-monsoon construction picks up','Steady year-end baseline']},
  'Energy':             {'states':['Normal','Normal','Normal','Recovery','Strong','Strong','Normal','Normal','Normal','Normal','Recovery','Normal'], 'confidence':'low',
    'why':['Steady baseline demand','Steady baseline demand','Steady baseline demand','Summer cooling demand starts building','Summer power demand near its annual high','Continued summer cooling demand','Demand normalizes post-summer','Demand normalizes post-summer','Demand normalizes post-summer','Demand normalizes post-summer','Winter demand starts picking up','Steady baseline winter demand']},
  'Oil & Gas':          {'states':['Normal','Normal','Normal','Recovery','Strong','Normal','Normal','Normal','Normal','Recovery','Normal','Normal'], 'confidence':'low',
    'why':['Steady baseline fuel demand','Steady baseline fuel demand','Steady baseline fuel demand','Summer travel demand starts building','Summer fuel demand near its annual high','Demand normalizes post-summer','Demand normalizes post-summer','Demand normalizes post-summer','Demand normalizes post-summer','Festive-travel fuel demand ticks up','Steady baseline demand','Steady baseline demand']},
  'Power':              {'states':['Normal','Normal','Recovery','Strong','Peak','Strong','Weak','Weak','Normal','Normal','Normal','Recovery'], 'confidence':'medium',
    'why':['Steady baseline demand, mild winter load','Steady baseline demand','Pre-summer cooling demand builds','Summer cooling demand rises','Peak summer cooling demand','Continued elevated summer demand','Monsoon/hydro substitution cuts thermal offtake','Continued monsoon hydro substitution','Demand normalizes post-monsoon','Steady baseline demand','Steady baseline demand','Winter heating load starts building']},
  'Realty':             {'states':['Normal','Normal','Strong','Weak','Weak','Weak','Recovery','Recovery','Strong','Peak','Peak','Strong'], 'confidence':'high',
    'why':['Steady baseline registrations','Steady baseline registrations','FY-end stamp-duty registration rush','Post FY-end registration lull','Summer heat softens site visits','Monsoon slows site visits & bookings','Bookings start picking up','Pre-festive interest builds','Pre-Diwali auspicious buying begins','Dhanteras/Diwali auspicious buying peaks','Continued festive & wedding-season buying','Wedding-season bookings remain elevated']},
  'Telecom':            {'states':['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Recovery','Recovery','Normal'], 'confidence':'low',
    'why':['Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Tariff/ARPU-driven, largely non-seasonal','Festive device & data-plan bump','Continued festive device demand','Demand normalizes post-festive']},
  'Manufacturing':      {'states':['Strong','Strong','Peak','Normal','Normal','Weak','Weak','Recovery','Recovery','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Pre-Budget capex positioning','Budget-linked order-book optimism','FY-end capex execution push','Post FY-end, steady execution','Post FY-end, steady execution','Monsoon disrupts logistics & output','Continued monsoon logistics disruption','Logistics & output start recovering','Production activity continues rebuilding','Steady baseline execution','Steady baseline execution','Steady baseline execution']},
  'Chemicals':          {'states':['Normal','Recovery','Strong','Strong','Normal','Strong','Peak','Strong','Normal','Recovery','Recovery','Normal'], 'confidence':'medium',
    'why':['Steady baseline demand','Pre-Kharif sowing prep begins','Sowing-season agrochemical demand builds','Continued pre-monsoon agrochemical demand','Demand steadies ahead of monsoon','Kharif sowing agrochemical demand rises','Peak Kharif sowing demand','Continued Kharif-season demand','Demand normalizes post-sowing','Rabi-season prep begins','Rabi sowing demand builds','Steady baseline demand']},
  'Insurance':          {'states':['Strong','Strong','Peak','Weak','Weak','Weak','Normal','Normal','Normal','Recovery','Recovery','Normal'], 'confidence':'high',
    'why':['80C tax-saving inflows begin','Tax-saving season builds momentum','80C deadline rush','Post tax-season lull','Seasonal trough, no major catalyst','Continued post-tax-season lull','Steady baseline policy sales','Steady baseline policy sales','Steady baseline policy sales','Festive-linked policy sales tick up','Continued festive-season sales','Demand normalizes into year-end']},
  'Defence':            {'states':['Normal','Strong','Strong','Normal','Normal','Normal','Normal','Recovery','Normal','Normal','Normal','Recovery'], 'confidence':'medium',
    'why':['Steady baseline, no major catalyst','Union Budget allocation lifts sentiment','FY-end contract execution push','Steady baseline order execution','Steady baseline order execution','Steady baseline order execution','Steady baseline order execution','Order pipeline starts rebuilding','Steady baseline activity','Steady baseline activity','Steady baseline activity','Year-end contract announcements build']},
  'PSU':                {'states':['Normal','Strong','Strong','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Steady baseline sentiment','Budget divestment/dividend news lifts sentiment','FY-end buyback announcements','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst']},
  'CPSE':               {'states':['Normal','Strong','Strong','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Steady baseline sentiment','Budget divestment/dividend news lifts sentiment','FY-end buyback announcements','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst']},
  'Bharat 22':          {'states':['Normal','Strong','Strong','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'medium',
    'why':['Steady baseline sentiment','Budget divestment/dividend news lifts sentiment','FY-end buyback announcements','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst','Steady baseline, no major catalyst']},
  'Digital India':      {'states':['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Strong','Peak','Normal'], 'confidence':'low',
    'why':['Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Steady baseline transaction volumes','Festive e-commerce sales events lift volumes','Peak festive UPI/e-commerce surge','Volumes normalize post-festive']},
  'ESG':                {'states':['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'low',
    'why':['Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal','Flow-driven, not meaningfully seasonal']},
  'Tourism':            {'states':['Strong','Strong','Recovery','Recovery','Strong','Weak','Weak','Weak','Recovery','Strong','Peak','Peak'], 'confidence':'high',
    'why':['Winter tourist season in full swing','Continued winter tourist demand','Winter season tapers off','Summer holiday bookings start building','Summer holiday travel at its secondary seasonal high','Monsoon onset dampens travel','Continued monsoon travel lull','Monsoon travel season remains soft','Post-monsoon bookings start recovering','Festive-season travel demand builds','Winter tourist season peaks','Year-end holiday travel peaks']},
  'Gold':               {'states':['Recovery','Normal','Normal','Strong','Strong','Normal','Normal','Recovery','Strong','Peak','Peak','Strong'], 'confidence':'high',
    'why':['Post-wedding-season demand tapers, restocking begins','Steady baseline demand','Steady baseline demand','Akshaya Tritiya buying builds','Continued Akshaya Tritiya-linked demand','Demand normalizes post-Akshaya Tritiya','Steady baseline demand','Pre-festive buying interest builds','Pre-Dhanteras stocking demand','Dhanteras — single biggest buying day','Wedding-season buying peaks','Continued wedding-season demand']},
  'Silver':             {'states':['Normal','Normal','Normal','Strong','Normal','Normal','Normal','Recovery','Strong','Peak','Peak','Strong'], 'confidence':'medium',
    'why':['Steady baseline, industrial + retail demand','Steady baseline demand','Steady baseline demand','Akshaya Tritiya buying builds','Demand normalizes post-Akshaya Tritiya','Steady baseline demand','Steady baseline demand','Pre-festive buying interest builds','Pre-Dhanteras stocking demand','Dhanteras festive buying peaks','Wedding-season buying peaks','Continued wedding-season demand']},
  'Copper':             {'states':['Recovery','Strong','Strong','Normal','Normal','Weak','Weak','Recovery','Normal','Normal','Recovery','Normal'], 'confidence':'low',
    'why':['China restocking demand begins','China construction-season restocking at its strongest','Continued China restocking demand','Demand normalizes post-restocking','Demand normalizes post-restocking','Monsoon slows domestic construction','Continued monsoon construction lull','Domestic demand starts rebuilding','Steady baseline, global-price driven','Steady baseline, global-price driven','Post-monsoon construction picks up','Steady year-end baseline']},
  'Crude Oil':          {'states':['Recovery','Normal','Normal','Recovery','Strong','Strong','Strong','Strong','Recovery','Normal','Strong','Peak'], 'confidence':'medium',
    'why':['Post-winter demand starts tapering','Steady baseline global demand','Steady baseline global demand','Pre-summer driving season builds','US summer driving season begins','Summer travel demand at its highest','Continued summer driving-season demand','Summer demand remains elevated','Summer season tapers off','Steady baseline, shoulder-season demand','Winter heating demand builds','Peak winter heating demand']},
  'Natural Gas':        {'states':['Peak','Strong','Weak','Weak','Weak','Recovery','Normal','Normal','Recovery','Strong','Strong','Peak'], 'confidence':'high',
    'why':['Peak winter heating demand','Continued elevated winter heating demand','Winter demand tapers off sharply','Shoulder-season demand trough','Continued shoulder-season lull','Early summer cooling demand builds','Steady baseline summer demand','Steady baseline summer demand','Pre-winter restocking begins','Winter-prep restocking demand rises','Early winter heating demand builds','Peak winter heating demand']},
  'Cement':             {'states':['Strong','Strong','Peak','Normal','Normal','Weak','Weak','Weak','Recovery','Recovery','Strong','Strong'], 'confidence':'medium',
    'why':['Pre-Budget construction activity picks up','Budget infra allocation lifts demand','FY-end construction push','Post FY-end, steady baseline demand','Post FY-end, steady baseline demand','Monsoon halts construction activity','Continued monsoon construction halt','Continued monsoon construction halt','Post-monsoon construction resumes','Site activity continues rebuilding','Post-monsoon construction demand rises','Year-end construction push continues']},
  'Railways':           {'states':['Normal','Strong','Strong','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'low',
    'why':['Steady baseline, no major catalyst','Union Budget rail capex allocation','FY-end execution push','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution','Steady baseline execution']},
  'EV Ecosystem':       {'states':['Normal','Strong','Normal','Normal','Normal','Normal','Normal','Recovery','Strong','Peak','Strong','Normal'], 'confidence':'low',
    'why':['Steady baseline demand','Budget FAME/PLI announcements lift sentiment','Steady baseline demand','Steady baseline demand','Steady baseline demand','Steady baseline demand','Steady baseline demand','Pre-festive launch pipeline builds','Festive EV launches align with Auto season','Festive-season EV sales peak','Continued festive-season demand','Demand normalizes post-festive']},
  'Innovation':         {'states':['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'low',
    'why':['No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver','No distinct seasonal driver']},
  'Logistics':          {'states':['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal'], 'confidence':'low',
    'why':['No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified','No distinct seasonal driver identified']},
}
